# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EvOkulu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EvOkulu
  pod 'Firebase/Core', '~> 6.13.0'
  pod 'Firebase/Messaging', '~> 6.13.0'

  target 'EvOkuluTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
